theme: jekyll-theme-cayman

sass:
  style: compressed

include:
- '_pages'
collections:
  pages:
    output: true
    permalink: /:path

permalink: pretty

exclude:
- 'node_modules'
- 'package.json'
- 'package-lock.json'
- 'vendor'
- 'default.nix'
- 'Gemfile'
- 'Gemfile.lock'
- 'gemset.nix'
- 'README.md'
