theme: jekyll-theme-cayman

sass:
  style: compressed

include:
- '_pages'
- '_pages/asunnot'
- '_pages/osakunta'
collections:
  pages:
    output: true
    permalink: /:path

permalink: pretty

exclude:
- 'node_modules'
- 'package.json'
- 'package-lock.json'
- 'vendor'
- 'Gemfile'
- 'Gemfile.lock'
- '*.nix'
- 'README.md'
